name: Debug Volleyball Kurs Check

on:
  workflow_dispatch:  # manuelles Starten erlaubt

jobs:
  run-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run Kurscheck
        run: python check_volleyball.py

      - name: Upload debug HTML as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug_html_output
          path: debug_output.html
